name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .npmrc for token authentication
        uses: healthplace/npmrc-registry-login-action@v1.0
        with:
          scope: '@benassa-de-glassa'
          registry: 'https://npm.pkg.github.com'
          auth-token: ${{secrets.GH_PACKAGE_READ_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/benassa-de-glassa/${{ github.event.repository.name }}:latest
          build-args: |
            PACKAGE_READ_TOKEN=${{ secrets.GITHUB_TOKEN }}
